"""Tests for reports/scripts/panoramax_api_census.py and the report it produced (#110).

Two halves, and the split is the standing rule in CLAUDE.md: **a committed-artifact pin proves nothing
about the code that produced it.** The artifact was generated by the current script, so a revert stays
green against it - every finding needs a synthetic, code-level test beside its corpus pin. So the
`TestReadingA...` classes drive the readers on hand-built items, and `TestTheReportMatchesTheArtifact`
checks the other failure this repo has actually shipped: a number hand-typed into a report's prose that
the artifact does not contain (two were wrong by 2x and 6x in the Mapillary census, section 6).

Network-free: nothing here calls the catalog.
"""

import json
import os
import sys

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SCRIPTS = os.path.join(REPO_ROOT, 'reports', 'scripts')
for path in (REPO_ROOT, SCRIPTS):
    if path not in sys.path:
        sys.path.insert(0, path)

import panoramax_api_census as census  # noqa: E402

ARTIFACT = os.path.join(REPO_ROOT, 'reports', 'data', '2026-09-08-panoramax-api.json')
REPORT = os.path.join(REPO_ROOT, 'reports', '2026-09-08-panoramax-api.md')


def item(pano_id='4ebd63bc-9b6f-4ea8-94d4-6eec2b6ce6a6', fov=360, sensor=(5760, 2880),
         matrix=(5760, 2880), host='panoramax.ign.fr', license_='etalab-2.0', producer='sig_bayonne'):
    """A STAC item shaped the way the catalog shapes one: everything but id/assets under `properties`."""
    interior = {'camera_manufacturer': 'GoPro', 'camera_model': 'Max'}
    if fov is not None:
        interior['field_of_view'] = fov
    if sensor is not None:
        interior['sensor_array_dimensions'] = list(sensor)
    properties = {'license': license_, 'geovisio:producer': producer,
                  'pers:interior_orientation': interior}
    if matrix is not None:
        properties['tiles:tile_matrix_sets'] = {'geovisio': {'tileMatrix': [
            {'tileWidth': 672.0, 'tileHeight': 672.0,
             'matrixWidth': matrix[0] / 672.0, 'matrixHeight': matrix[1] / 672.0}]}}
    return {'id': pano_id, 'type': 'Feature',
            'assets': {'hd': {'href': 'https://%s/api/pictures/%s/hd.jpg' % (host, pano_id)}},
            'properties': properties}


@pytest.fixture(scope='module')
def artifact():
    with open(ARTIFACT, encoding='utf-8') as f:
        return json.load(f)


@pytest.fixture(scope='module')
def report_text():
    with open(REPORT, encoding='utf-8') as f:
        return f.read()


class TestReadingAnItemsFieldOfView:
    def test_it_is_read_from_properties_not_from_the_top_level(self):
        """The defect this exists for. `assets` is top-level and `pers:interior_orientation` is not, and
        the downloader's first version read the latter where the former lives - so it returned None for
        every picture ever served and the projection guard never fired, with every other test still green.
        A top-level copy must NOT rescue a reader that looks in the wrong place."""
        nested = item(fov=92)
        top_level_only = {'id': 'x', 'assets': {},
                          'pers:interior_orientation': {'field_of_view': 92}, 'properties': {}}

        assert census.field_of_view(nested) == 92
        assert census.field_of_view(top_level_only) is None

    @pytest.mark.parametrize('properties', [{}, {'pers:interior_orientation': None},
                                            {'pers:interior_orientation': 'not an object'},
                                            {'pers:interior_orientation': {}}])
    def test_an_unstated_field_of_view_reads_as_none_not_as_zero(self, properties):
        """Undefined is not zero, and it is not 360 either: a study that coerced this would silently
        reclassify a whole arm of the corpus."""
        assert census.field_of_view({'id': 'x', 'properties': properties}) is None


class TestReadingAnItemsDimensions:
    def test_the_tile_matrix_multiplies_out_to_the_frame(self):
        assert census.tile_matrix_dims(item(matrix=(5760, 2880))) == (5760, 2880)
        assert census.tile_matrix_dims(item(matrix=(5376, 2688))) == (5376, 2688)

    def test_sensor_dimensions_come_back_as_a_pair_of_ints(self):
        assert census.sensor_dims(item(sensor=(5376, 2688))) == (5376, 2688)
        assert census.sensor_dims(item(sensor=None)) is None
        assert census.sensor_dims({'id': 'x', 'properties': {}}) is None

    @pytest.mark.parametrize('properties', [
        {},
        {'tiles:tile_matrix_sets': {}},
        {'tiles:tile_matrix_sets': {'geovisio': {}}},
        {'tiles:tile_matrix_sets': {'geovisio': {'tileMatrix': []}}},
    ], ids=['absent', 'empty', 'no tileMatrix key', 'empty tileMatrix'])
    def test_a_missing_tile_matrix_reads_as_none(self, properties):
        assert census.tile_matrix_dims({'id': 'x', 'properties': properties}) is None

    def test_a_disagreement_between_the_two_sources_is_counted_and_shown(self):
        """The measurement is worth making only because the two CAN disagree - the viewer writes one into
        pano_data and the downloader stores a file whose size is the other, so a disagreement is every
        label in the city skipped by the cropper's dims_mismatch preflight. This is the synthetic proof
        that the counter would notice; the artifact's 677/0 is the corpus pin beside it."""
        features = [item(pano_id='a', sensor=(5760, 2880), matrix=(5760, 2880)),
                    item(pano_id='b', sensor=(4000, 2000), matrix=(5760, 2880)),
                    item(pano_id='c', sensor=None, matrix=(5760, 2880))]

        result = census.dimension_agreement(features)

        assert (result['agree'], result['disagree'], result['not_stated']) == (1, 1, 1)
        assert result['disagreements'] == [{'id': 'b', 'sensor': [4000, 2000],
                                            'tile_matrix': [5760, 2880]}]
        assert result['frame_sizes'] == {'5760x2880': 3}

    def test_only_panoramas_are_counted(self):
        """A flat picture's dimensions are not a finding about the frame we store."""
        result = census.dimension_agreement([item(pano_id='flat', fov=92, sensor=(4000, 2020),
                                                  matrix=(4000, 2020))])

        assert (result['agree'], result['disagree'], result['not_stated']) == (0, 0, 0)
        assert result['frame_sizes'] == {}


class TestClassifyingTheBbox:
    def test_the_split_is_on_field_of_view_and_nothing_else(self):
        """Not on producer, licence or host, all three of which happen to separate the two arms in Bayonne
        and none of which is guaranteed to anywhere else - a city could be surveyed by two contributors, or
        one contributor could upload both kinds."""
        features = [item(pano_id='a', fov=360, producer='sig_bayonne'),
                    item(pano_id='b', fov=360, producer='someone_else', license_='CC-BY-4.0'),
                    item(pano_id='c', fov=92, producer='sig_bayonne')]

        result = census.classify(features)

        assert result['examined'] == 3
        assert result['panoramic']['count'] == 2
        assert result['other']['count'] == 1
        assert result['panoramic']['licenses'] == {'etalab-2.0': 1, 'CC-BY-4.0': 1}
        assert result['other']['field_of_view_values'] == {'92': 1}

    def test_a_picture_with_no_stated_field_of_view_is_not_counted_as_panoramic(self):
        """The census and the downloader deliberately disagree here, and the report says so: the downloader
        DOWNLOADS an unstated fov (absence of evidence is not a verdict, #99) while the census refuses to
        COUNT it as a measured panorama. Conflating the two would let an unstated picture inflate the very
        number that justifies the guard."""
        result = census.classify([item(fov=None)])

        assert result['panoramic']['count'] == 0
        assert result['other']['count'] == 1

    def test_an_empty_bbox_yields_no_share_rather_than_a_zero_division(self):
        """Undefined is not zero: 0 of 0 pictures is not 0% panoramic. `f"{None:.1f}"` is the crash this
        repo found in four scripts at once, so the share has to be None and main() has to print it
        through studyfmt.fmt."""
        result = census.classify([])

        assert result['panoramic_share_pct'] is None
        assert census.fmt(result['panoramic_share_pct'], '.1f') == 'n/a'


class TestTheArtifactIsWellFormed:
    def test_it_carries_every_section_the_report_reads(self, artifact):
        assert set(artifact) >= {'bbox', 'catalog', 'composition', 'dimensions',
                                 'id_resolution', 'absence', 'hd_headers'}

    def test_the_two_arms_account_for_every_picture_examined(self, artifact):
        composition = artifact['composition']
        assert composition['panoramic']['count'] + composition['other']['count'] == composition['examined']

    def test_the_dimension_tallies_account_for_every_panorama(self, artifact):
        dims, composition = artifact['dimensions'], artifact['composition']
        assert dims['agree'] + dims['disagree'] + dims['not_stated'] == composition['panoramic']['count']
        assert sum(dims['frame_sizes'].values()) == composition['panoramic']['count']

    def test_absence_is_a_404_at_pictures_and_a_200_at_search(self, artifact):
        """The finding the whole ledger design rests on. If this ever flips, downloaders/panoramax.py's
        404 branch is writing permanent rows on a body that no longer means what it meant."""
        absence = artifact['absence']
        assert absence['pictures_endpoint']['status'] == 404
        assert absence['pictures_endpoint']['body'] == {'status': 404, 'message': 'Feature not found'}
        assert absence['search_endpoint']['status'] == 200
        assert absence['search_endpoint']['features_returned'] == 0

    def test_the_asset_href_is_on_a_different_host_than_the_catalog(self, artifact):
        """Why the href is followed and never built."""
        href = artifact['id_resolution']['pictures_endpoint']['hd_href']
        assert href.startswith('https://')
        assert href.split('/')[2] not in artifact['catalog']


class TestTheReportMatchesTheArtifact:
    """Every number in the write-up's prose is transcribed from the artifact, and this says so.

    The failure it guards is measured, not imagined: two counts hand-typed into
    reports/2026-08-11-mapillary-census.md were wrong by 2x and 6x, and nothing about the surrounding
    sentences looked different for it. A report table is the one place in this repo where a plausible
    number has no compiler and no test behind it.
    """

    def quoted(self, artifact):
        composition, dims, headers = (artifact['composition'], artifact['dimensions'],
                                      artifact['hd_headers'])
        sizes = sorted(dims['frame_sizes'], key=lambda k: -dims['frame_sizes'][k])
        return {
            'pictures examined': '**1,000**' if composition['examined'] == 1000
                                 else '**%d**' % composition['examined'],
            'panoramic count': '**%d**' % composition['panoramic']['count'],
            'other count': '**%d**' % composition['other']['count'],
            'panoramic share': '**%.1f%%**' % composition['panoramic_share_pct'],
            'panoramic licence': '`%s`' % list(composition['panoramic']['licenses'])[0],
            'other licence': '`%s`' % list(composition['other']['licenses'])[0],
            'panoramic producer': '`%s`' % list(composition['panoramic']['producers'])[0],
            'other producer': '`%s`' % list(composition['other']['producers'])[0],
            'panoramic host': '`%s`' % list(composition['panoramic']['asset_hosts'])[0],
            'other host': '`%s`' % list(composition['other']['asset_hosts'])[0],
            'other field of view': list(composition['other']['field_of_view_values'])[0],
            'dims agree': '**%d agree**' % dims['agree'],
            'dims disagree': '**%d disagree**' % dims['disagree'],
            'dims not stated': '**%d not stated**' % dims['not_stated'],
            'largest frame': sizes[0].replace('x', '×'),
            'largest frame count': '**%d**' % dims['frame_sizes'][sizes[0]],
            'second frame': sizes[1].replace('x', '×'),
            'second frame count': '**%d**' % dims['frame_sizes'][sizes[1]],
            'hd header checks': '**%d of %d**' % (headers['agree'], headers['checked']),
            'absent uuid': artifact['absence']['absent_uuid'],
            'absent status': '**%d**' % artifact['absence']['pictures_endpoint']['status'],
            'search features': '**%d** features'
                               % artifact['absence']['search_endpoint']['features_returned'],
            'resolution status': '**%d**' % artifact['id_resolution']['pictures_endpoint']['status'],
        }

    def test_the_transcription_list_is_not_vacuous(self, artifact):
        """Guards the guard: a refactor that emptied `quoted` would make every assertion below pass over
        nothing."""
        assert len(self.quoted(artifact)) >= 20

    def test_every_quoted_value_appears_in_the_report(self, artifact, report_text):
        missing = {label: value for label, value in self.quoted(artifact).items()
                   if value not in report_text}
        assert not missing, 'in the artifact but not transcribed into the report: %s' % missing

    def test_the_404_body_is_quoted_verbatim(self, artifact, report_text):
        body = artifact['absence']['pictures_endpoint']['body']
        assert '"status": %d' % body['status'] in report_text
        assert '"message": "%s"' % body['message'] in report_text

    def test_the_downloaders_guard_and_the_census_share_one_definition_of_panoramic(self):
        """Two constants named the same thing in two files is how they drift - and pinning the CONSTANT
        does not stop it, which is how it drifted anyway (found 2026-09-10): the downloader's comparison
        became tolerant (`"360"`, 359.9997, a Decimal) inside the same PR that this test watched, while the
        census kept an exact `== 360`. The constant matched the whole time. So the census imports the
        downloader's predicate rather than restating the rule, the same way no study may grow a local copy
        of studyfmt.fmt, and this asserts it is the one function rather than an equal-looking one.
        """
        import downloaders.panoramax as panoramax

        assert panoramax.PANORAMIC_FIELD_OF_VIEW_DEG == 360
        assert census.is_panoramic_field_of_view is panoramax.is_panoramic_field_of_view
        assert not hasattr(census, 'PANORAMIC_FIELD_OF_VIEW_DEG'), (
            'a local copy of the constant is how the rule drifted the first time')

    def test_the_census_classifies_by_the_downloaders_rule_not_by_an_exact_360(self):
        """The arms are what the report's percentages are computed over, so a value the downloader would
        treat as a panorama has to land in the panoramic arm here too - otherwise the census stops
        predicting what the scraper will do with the bbox, which is the only reason it was measured."""
        features = [item(pano_id='a', fov=360), item(pano_id='b', fov='360'),
                    item(pano_id='c', fov=359.9997), item(pano_id='d', fov=92),
                    item(pano_id='e', fov=None)]

        composition = census.classify(features)

        assert composition['panoramic']['count'] == 3
        assert composition['other']['count'] == 2

    def test_the_census_and_the_downloader_agree_on_the_catalog(self):
        import downloaders.panoramax as panoramax

        assert census.CATALOG_API_BASE == panoramax.CATALOG_API_BASE
