"""Every figure the Phase 2a report and amendment 2 quote must come from a committed manifest.

A report table is the one place in this repo where a plausible number has no compiler and no test
behind it, and this series has already shipped two hand-typed counts wrong by 2x and 6x, plus a
filtered count (81,667 eligible) quoted as a raw one (82,769). So the numbers are not re-derived here
and then compared to prose — they are read out of the artifact the draw wrote, and the prose is
asserted to contain them.

This file deliberately tests the *documents*. The behaviour of the code that produced the artifacts is
covered separately in test_corpus_sample.py, because pinning a finding against a committed artifact
proves nothing about the function that produced it: the artifact was generated BY the current code, so
a revert stays green.
"""

import json
import os

import pytest

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
REPORTS = os.path.join(REPO_ROOT, 'reports')
DATA = os.path.join(REPORTS, 'data')

REPORT = os.path.join(REPORTS, '2026-08-12-corpus-assembly.md')
PREREG = os.path.join(REPORTS, '2026-08-09-crop-priors-prereg.md')
GSV = os.path.join(DATA, '2026-08-12-crop-corpus-gsv.json')
MAPILLARY = os.path.join(DATA, '2026-08-12-crop-corpus-mapillary.json')


def _load(path):
    with open(path, encoding='utf-8') as f:
        return json.load(f)


def _text(path):
    """The document with every whitespace run collapsed to one space.

    Prose wraps, and a phrase this file asserts on can fall across a line break — `*not\\nestimable*`
    is not the substring `not estimable`. Without normalizing, the fix for a failing prose assertion
    looks like "reword the report", which is how a check on a report's contents quietly becomes a check
    on its line breaks.
    """
    with open(path, encoding='utf-8') as f:
        return ' '.join(f.read().split())


@pytest.fixture(scope='module')
def gsv():
    return _load(GSV)


@pytest.fixture(scope='module')
def mapillary():
    return _load(MAPILLARY)


@pytest.fixture(scope='module')
def report():
    return _text(REPORT)


@pytest.fixture(scope='module')
def prereg():
    return _text(PREREG)


def _n(value):
    """A count as the reports write it, with a thousands separator."""
    return f'{int(value):,}'


class TestTheArtifactsExist:
    """Guards the guards: every assertion below reads these files, so a rename would otherwise make the
    whole module vacuous rather than failing."""

    def test_both_manifests_and_both_corpora_are_committed(self):
        for path in (GSV, MAPILLARY, REPORT,
                     os.path.join(DATA, '2026-08-12-crop-corpus-gsv.csv.gz'),
                     os.path.join(DATA, '2026-08-12-crop-corpus-mapillary.csv.gz')):
            assert os.path.exists(path), path

    def test_the_manifests_record_their_provenance(self, gsv, mapillary):
        """A draw that does not say which bytes it read cannot be audited later, and rawLabels moves."""
        for m in (gsv, mapillary):
            assert m['fetched'] == '2026-08-12'
            assert m['seed'] == 20260812
            assert m['provenance'], 'no per-file hashes recorded'
            for rec in m['provenance']:
                assert len(rec['sha256']) == 64
                assert rec['n_rows'] > 0
        assert len(gsv['provenance']) == 49
        assert len(mapillary['provenance']) == 1


class TestTheDrawMatchesTheReport:

    def test_the_headline_counts(self, gsv, report):
        d = gsv['draw']
        assert d['n_labels'] == 763 and d['n_panos'] == 661
        assert d['n_measurable'] == 584
        for value in (d['n_labels'], d['n_panos'], d['n_measurable'], len(d['by_city'])):
            assert str(value) in report, value

    def test_the_frame_counts(self, gsv, report):
        f = gsv['frame']
        assert f['n_cities'] == 49
        for value in (f['n_labels'], f['n_corpus_eligible'], f['n_measurable'], f['n_panos']):
            assert _n(value) in report, value

    def test_every_cell_reaches_the_target(self, gsv, report):
        """The claim the corpus stands on: 120 of 120 cells at or above target, none below."""
        strata = gsv['draw']['strata']
        at_target = sum(1 for v in strata.values() if v == 6)
        above = sum(1 for v in strata.values() if v > 6)
        below = sum(1 for v in strata.values() if v < 6)
        assert (len(strata), at_target, above, below) == (120, 112, 8, 0)
        assert '120 of 120' in report
        assert '**112 at exactly 6**' in report

    def test_the_forced_strata_achievements(self, gsv, report):
        s = gsv['draw']['shortfalls']
        assert (s['contrast_panos']['achieved'], s['contrast_panos']['required']) == (81, 80)
        assert (s['resolution']['achieved'], s['resolution']['required']) == (122, 60)
        assert (s['mismatch']['achieved'], s['mismatch']['required']) == (48, 30)
        for a, r in ((81, 80), (122, 60), (48, 30)):
            assert f'**{a}/{r}**' in report, (a, r)

    def test_no_gsv_stratum_is_short(self, gsv):
        assert all(v['shortfall'] == 0 for v in gsv['draw']['shortfalls'].values())

    def test_the_reweighting_is_fully_supported(self, gsv, report):
        cov = gsv['draw']['weight_coverage']
        assert cov['cells_total'] == 32 and cov['cells_unsupported'] == 0
        assert cov['unsupported_population_pct'] == pytest.approx(0.0)
        assert '**32**' in report and '**0.00%**' in report

    def test_the_split_is_by_pano_and_balanced(self, gsv, report):
        by_split = gsv['draw']['by_split']
        assert by_split == {'tune': 388, 'eval': 375}
        assert '388 / 375' in report

    def test_the_per_pano_cap_held(self, gsv):
        assert gsv['draw']['labels_per_pano_max'] <= gsv['spec']['max_labels_per_pano'] == 3

    def test_the_per_band_counts_are_reported_under_both_filters(self, gsv, report, prereg):
        """§5's power table is per depression band, and the corpus figure is 30% higher than the one
        Study 1 actually gets. Both belong in the manifest under names that say which filter they are
        under, and both documents must quote the pair rather than the flattering half.
        """
        d = gsv['draw']
        corpus, measurable = d['by_band'], d['by_band_measurable']
        assert sum(corpus.values()) == d['n_labels'] == 763
        assert sum(measurable.values()) == d['n_measurable'] == 584
        assert all(measurable[b] <= corpus[b] for b in corpus)
        # Rounded to one decimal, which is how both documents print it — 763/4 is 190.75, and
        # asserting a tolerance around the printed value instead just re-litigates float spacing.
        assert round(sum(corpus.values()) / 4, 1) == 190.8
        assert round(sum(measurable.values()) / 4, 1) == 146.0
        assert min(measurable.values()) == 137 and max(measurable.values()) == 155
        assert min(corpus.values()) == 180 and max(corpus.values()) == 205
        for doc in (report, prereg):
            assert '190.8' in doc and '146.0' in doc
            assert '137' in doc

    def test_the_thinnest_band_still_clears_the_registered_power_requirement(self, gsv):
        """The conclusion the corrected figures have to support: 44 per stratum for delta = 0.25 deg at
        sigma_gold 0.30, ~57 after §5's stated design effect of ~1.3 for pano clustering."""
        assert min(gsv['draw']['by_band_measurable'].values()) > 44 * 1.3


class TestTheFrameComparisonMatchesBothDocuments:
    """The evidence for amendment 2(a). Quoted in two documents, so both are checked against the one
    artifact — a figure that agrees with the report but not the amendment is the failure mode here."""

    def test_the_reference_share(self, gsv, report, prereg):
        fc = gsv['frame_comparison']
        assert fc['applicable'] is True
        assert fc['reference_share_pct'] == pytest.approx(31.98, abs=0.01)
        assert fc['n_reference_corpus_eligible'] == 431276
        assert fc['n_frame_corpus_eligible'] == 1348743
        for doc in (report, prereg):
            assert '31.98%' in doc
            assert '431,276 of 1,348,743' in doc

    def test_the_total_variation_distances(self, gsv, report, prereg):
        tv = gsv['frame_comparison']['total_variation_pct']
        assert tv['quality'] == pytest.approx(43.16, abs=0.01)
        assert tv['band_x_type'] == pytest.approx(11.34, abs=0.01)
        assert tv['label_type'] == pytest.approx(11.06, abs=0.01)
        assert tv['band'] == pytest.approx(3.35, abs=0.01)
        for doc in (report, prereg):
            assert '43.16' in doc
        assert '11.34 pp' in prereg
        for value in ('11.06', '3.35'):
            assert value in report, value

    @pytest.mark.parametrize('stratum,ref,frame,ratio', [
        ('post_fix', 9.98, 46.34, 4.64),
        ('window', 10.74, 17.54, 1.63),
        ('mid', 45.54, 21.76, 0.48),
        ('legacy', 33.75, 14.36, 0.43),
    ])
    def test_the_era_quality_table(self, gsv, report, prereg, stratum, ref, frame, ratio):
        """The row the amendment turns on. Every cell of the printed table, in both documents."""
        row = gsv['frame_comparison']['by_quality'][stratum]
        assert row['reference_pct'] == pytest.approx(ref, abs=0.01)
        assert row['frame_pct'] == pytest.approx(frame, abs=0.01)
        assert row['ratio'] == pytest.approx(ratio, abs=0.005)
        for doc in (report, prereg):
            assert f'{ref:.2f}%' in doc, (stratum, ref)
            assert f'{frame:.2f}%' in doc, (stratum, frame)
            assert f'{ratio:.2f}×' in doc, (stratum, ratio)

    @pytest.mark.parametrize('label_type,ratio', [
        ('Signal', 3.00), ('Crosswalk', 2.56), ('NoSidewalk', 1.19), ('Obstacle', 1.05),
        ('SurfaceProblem', 0.97), ('CurbRamp', 0.88), ('NoCurbRamp', 0.57), ('Other', 0.53),
    ])
    def test_the_label_type_table_in_the_amendment(self, gsv, prereg, label_type, ratio):
        """All eight types, because the first version of this table showed only the four biggest
        shifts and left a reader asking where SurfaceProblem went."""
        row = gsv['frame_comparison']['by_label_type'][label_type]
        assert row['ratio'] == pytest.approx(ratio, abs=0.005)
        assert f'{ratio:.2f}×' in prereg, (label_type, ratio)

    def test_the_six_cities_already_occupy_every_cell(self, gsv, report, prereg):
        """The property that licenses reweighting a narrow draw to a wide population."""
        cells = gsv['frame_comparison']['strata_cells']
        assert cells['reference'] == cells['frame'] == 120
        assert cells['only_in_frame'] == [] and cells['only_in_reference'] == []
        for doc in (report, prereg):
            assert '120 of 120' in doc

    def test_the_reference_is_the_six_phase_one_cities(self, gsv):
        assert gsv['frame_comparison']['reference_cities'] == [
            'amsterdam', 'cdmx', 'columbus-oh', 'newberg-or', 'oradell-nj', 'seattle-wa']


class TestTheMapillaryArmMatchesTheReport:

    def test_its_size_and_shortfalls(self, mapillary, report, prereg):
        f, d = mapillary['frame'], mapillary['draw']
        assert (f['n_labels'], f['n_corpus_eligible'], f['n_measurable'], f['n_panos']) == \
            (267, 264, 181, 89)
        assert (d['n_labels'], d['n_panos']) == (97, 44)
        assert d['shortfalls']['contrast_panos']['achieved'] == 40
        assert d['shortfalls']['mismatch']['achieved'] == 0
        for doc in (report, prereg):
            assert '**97 labels over 44 panos**' in doc or '**97**' in doc

    def test_the_within_pano_column_is_not_estimable_there(self, mapillary, report, prereg):
        """40 separated panos against §2.3's gate of 60. Stated in both documents now rather than
        discovered after the annotation is paid for."""
        gate = mapillary['spec']['contrast_estimability_gate']
        assert gate == 60
        assert mapillary['draw']['shortfalls']['contrast_panos']['achieved'] < gate
        assert 'not estimable' in report
        assert 'not estimable' in prereg

    def test_the_frame_comparison_is_reported_as_not_applicable(self, mapillary):
        """Against a disjoint reference every total-variation distance is exactly 50.00 pp — a
        clean-looking number that means nothing. It must not be published as one."""
        fc = mapillary['frame_comparison']
        assert fc['applicable'] is False
        assert 'total_variation_pct' not in fc
        assert '50.0' not in json.dumps(fc)


class TestTheDefectsAreRecorded:
    """The wrong turns, which reports/README.md requires explicitly and which never survive into a
    commit message."""

    def test_the_label_id_collision_is_written_down(self, report, prereg):
        for doc in (report, prereg):
            assert '90,369 of 316,735' in doc
        assert '449 labels instead of 763' in report
        assert 'label_uid' in report

    def test_the_stratum_tally_overshoot_is_written_down(self, report):
        assert '96/60' in report

    def test_the_excluded_deployments_are_named_with_counts(self, gsv, report, prereg):
        excluded = {e['city']: e for e in gsv['excluded_deployments']}
        assert set(excluded) == {'validation-study', 'la-piedad-old', 'richmond-va',
                                 'zurich-infra3d'}
        assert excluded['validation-study']['n_rows'] == 10809
        assert excluded['la-piedad-old']['n_rows'] == 4391
        assert excluded['zurich-infra3d']['n_rows'] == 4791
        for doc in (report, prereg):
            assert '10,809' in doc and '4,391' in doc and '4,791' in doc

    def test_the_store_probe_is_named_as_a_gate(self, report, prereg):
        """Amendment 2(a) is conditional: the 99.2% coverage figure was measured on six cities, and the
        corpus cannot freeze until a probe covers the drawn panos."""
        assert 'unmeasured' in report
        assert 'does **not** freeze' in prereg


class TestTheAmendmentIsWellFormed:

    def test_it_is_appended_after_amendment_one(self, prereg):
        assert prereg.index('### Amendment 1') < prereg.index('### Amendment 2')

    def test_it_is_dated_and_precedes_any_annotation(self, prereg):
        assert '### Amendment 2 — 2026-08-12' in prereg
        assert 'before any annotation exists' in prereg

    def test_it_states_what_it_does_not_change(self, prereg):
        """An amendment that silently touched the endpoints or the power table would invalidate the
        registration it is appended to."""
        head = prereg[prereg.index('### Amendment 2'):]
        assert 'endpoints, decision rules, annotation protocol and power table all stand' in head

    def test_it_supersedes_section_six_on_mapillary(self, prereg):
        head = prereg[prereg.index('### Amendment 2'):]
        assert "replacing §6's blanket exclusion of Mapillary" in head
